"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 18:19:09.434700
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('external_ref', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('home_country', sa.CHAR(length=2), nullable=False),
    sa.Column('home_city', sa.String(length=80), nullable=False),
    sa.Column('segment', sa.String(length=16), server_default='retail', nullable=False),
    sa.Column('customer_since', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("segment IN ('retail', 'premium', 'business')", name=op.f('ck_customers_segment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('email', name=op.f('uq_customers_email')),
    sa.UniqueConstraint('external_ref', name=op.f('uq_customers_external_ref'))
    )
    op.create_table('merchants',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('external_ref', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mcc', sa.CHAR(length=4), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('country', sa.CHAR(length=2), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mcc ~ '^[0-9]{4}$'", name=op.f('ck_merchants_mcc_format')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchants')),
    sa.UniqueConstraint('external_ref', name=op.f('uq_merchants_external_ref'))
    )
    op.create_index(op.f('ix_merchants_category'), 'merchants', ['category'], unique=False)
    op.create_table('customer_profiles',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('avg_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('median_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tx_count_90d', sa.Integer(), nullable=False),
    sa.Column('usual_countries', postgresql.ARRAY(sa.CHAR(length=2)), nullable=False),
    sa.Column('usual_merchant_categories', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('active_hour_start', sa.SmallInteger(), nullable=False),
    sa.Column('active_hour_end', sa.SmallInteger(), nullable=False),
    sa.Column('trusted_device_count', sa.Integer(), nullable=False),
    sa.Column('last_transaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('active_hour_start BETWEEN 0 AND 23 AND active_hour_end BETWEEN 0 AND 23', name=op.f('ck_customer_profiles_active_hours')),
    sa.CheckConstraint('tx_count_90d >= 0', name=op.f('ck_customer_profiles_tx_count_non_negative')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_profiles_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_customer_profiles'))
    )
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('device_type', sa.String(length=16), nullable=False),
    sa.Column('os', sa.String(length=40), nullable=True),
    sa.Column('is_trusted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("device_type IN ('mobile', 'tablet', 'desktop', 'emulator', 'unknown')", name=op.f('ck_devices_device_type')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_devices_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('customer_id', 'fingerprint', name=op.f('uq_devices_customer_id_fingerprint'))
    )
    op.create_index(op.f('ix_devices_customer_id'), 'devices', ['customer_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), server_default='KZT', nullable=False),
    sa.Column('country', sa.CHAR(length=2), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('channel', sa.String(length=16), server_default='card_present', nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('is_vpn', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='received', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('card_present', 'online', 'transfer')", name=op.f('ck_transactions_channel')),
    sa.CheckConstraint("status IN ('received', 'investigating', 'verified', 'approved', 'blocked')", name=op.f('ck_transactions_status')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_transactions_amount_positive')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_transactions_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_transactions_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_transactions_merchant_id_merchants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('reference', name=op.f('uq_transactions_reference'))
    )
    op.create_index('ix_transactions_customer_id_occurred_at', 'transactions', ['customer_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_transactions_device_id'), 'transactions', ['device_id'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_transactions_occurred_at'), 'transactions', ['occurred_at'], unique=False)
    op.create_index('ix_transactions_status_occurred_at', 'transactions', ['status', 'occurred_at'], unique=False)
    op.create_table('fraud_labels',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('labeled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("label IN ('fraud', 'legit')", name=op.f('ck_fraud_labels_label')),
    sa.CheckConstraint("source IN ('chargeback', 'analyst', 'customer_confirmation', 'rule')", name=op.f('ck_fraud_labels_source')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_fraud_labels_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fraud_labels')),
    sa.UniqueConstraint('transaction_id', 'source', name=op.f('uq_fraud_labels_transaction_id_source'))
    )
    op.create_index(op.f('ix_fraud_labels_label'), 'fraud_labels', ['label'], unique=False)
    op.create_index(op.f('ix_fraud_labels_transaction_id'), 'fraud_labels', ['transaction_id'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('shap_values', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 1', name=op.f('ck_model_predictions_score_range')),
    sa.CheckConstraint('threshold >= 0 AND threshold <= 1', name=op.f('ck_model_predictions_threshold_range')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_model_predictions_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_predictions'))
    )
    op.create_index('ix_model_predictions_model_name_model_version', 'model_predictions', ['model_name', 'model_version'], unique=False)
    op.create_index('ix_model_predictions_transaction_id_created_at', 'model_predictions', ['transaction_id', 'created_at'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('prediction_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=24), server_default='open', nullable=False),
    sa.Column('initial_risk', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('final_risk', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'running', 'awaiting_verification', 'closed')", name=op.f('ck_investigations_status')),
    sa.CheckConstraint('final_risk IS NULL OR final_risk BETWEEN 0 AND 100', name=op.f('ck_investigations_final_risk_range')),
    sa.CheckConstraint('initial_risk BETWEEN 0 AND 100', name=op.f('ck_investigations_initial_risk_range')),
    sa.ForeignKeyConstraint(['prediction_id'], ['model_predictions.id'], name=op.f('fk_investigations_prediction_id_model_predictions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_investigations_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigations'))
    )
    op.create_index(op.f('ix_investigations_prediction_id'), 'investigations', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_investigations_status'), 'investigations', ['status'], unique=False)
    op.create_index(op.f('ix_investigations_transaction_id'), 'investigations', ['transaction_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('outcome', sa.String(length=8), nullable=False),
    sa.Column('final_risk', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.String(length=8), server_default='system', nullable=False),
    sa.Column('analyst_name', sa.String(length=120), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decided_by IN ('system', 'analyst')", name=op.f('ck_decisions_decided_by')),
    sa.CheckConstraint("outcome IN ('APPROVED', 'BLOCKED', 'VERIFY')", name=op.f('ck_decisions_outcome')),
    sa.CheckConstraint('final_risk BETWEEN 0 AND 100', name=op.f('ck_decisions_final_risk_range')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_decisions_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_decisions_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_index(op.f('ix_decisions_investigation_id'), 'decisions', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_decisions_transaction_id'), 'decisions', ['transaction_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('trust', sa.String(length=8), nullable=False),
    sa.Column('impact', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('found_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("trust IN ('HIGH', 'MEDIUM', 'LOW')", name=op.f('ck_evidence_trust')),
    sa.CheckConstraint('impact BETWEEN -100 AND 100', name=op.f('ck_evidence_impact_range')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_evidence_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence')),
    sa.UniqueConstraint('investigation_id', 'position', name=op.f('uq_evidence_investigation_id_position'))
    )
    op.create_table('verification_events',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('push', 'sms', 'call', 'biometric')", name=op.f('ck_verification_events_method')),
    sa.CheckConstraint("status IN ('sent', 'confirmed', 'failed', 'expired')", name=op.f('ck_verification_events_status')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_verification_events_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_events'))
    )
    op.create_index(op.f('ix_verification_events_investigation_id'), 'verification_events', ['investigation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_events_investigation_id'), table_name='verification_events')
    op.drop_table('verification_events')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_decisions_transaction_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_investigation_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_investigations_transaction_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_status'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_prediction_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index('ix_model_predictions_transaction_id_created_at', table_name='model_predictions')
    op.drop_index('ix_model_predictions_model_name_model_version', table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index(op.f('ix_fraud_labels_transaction_id'), table_name='fraud_labels')
    op.drop_index(op.f('ix_fraud_labels_label'), table_name='fraud_labels')
    op.drop_table('fraud_labels')
    op.drop_index('ix_transactions_status_occurred_at', table_name='transactions')
    op.drop_index(op.f('ix_transactions_occurred_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_device_id'), table_name='transactions')
    op.drop_index('ix_transactions_customer_id_occurred_at', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_devices_customer_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('customer_profiles')
    op.drop_index(op.f('ix_merchants_category'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_table('customers')
    # ### end Alembic commands ###
